# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: tarefas
  pool: 5
  username: postgres
  password: wanesuh

test:
  adapter: postgresql
  encoding: unicode
  database: tarefas
  pool: 5
  username: postgres
  password: wanesuh
