# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c334d6e26fd25968a2e34e79949734edd3bf71a82ae8ddd9898643c75baa7733387223814d297a2cfaf00f8580172b8ea058ea7e66b3209cc50f2249822e7ac

test:
  secret_key_base: 0dc5eec5e9d299a203fb03bfea1f4904e921f9cb549f2708f54e2d57a749285220a9457611291f6d9e2fc604665dd7a13e770f5a5f3c171dc363a8010310cdaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
